# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "/Users/martiniak/Developer/GitHub/Burgyn/Codecon.Caching"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Codecon.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "codecon.api:dev"
    ports: []
    volumes:
    - "/Users/martiniak/Developer/GitHub/Burgyn/Codecon.Caching/src/Codecon.Api:/app:rw"
    - "/Users/martiniak/Developer/GitHub/Burgyn/Codecon.Caching:/src:rw"
    - "/Users/martiniak/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
